Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
                  HELLO USER
              WELLCOME TO OUR LIBARY
ENTER YOUR PASSWORD PLEASEANUABHVAS
ENTER THE SECTION THE SECTION EHICH YOU WANT TO INQUIRE TODAY
PRESS 1 FOR BOOKS
PRESS 2 FOR MAGZINE
PRESS 3 FOR NEWSPAPER
PRESS 4 FOR QUIT
1
ENTER THE TASK YOU WANT TO PERFORM
PRESS 1 FOR ADDING NEW BOOK TO THE LIBARY
PRESS 2 FOR BORROWING A BOOK FROM LIBARY
PRESS 3 FOR DISPLAYING ALL BOOK OF THE LIBARY
PRESS 4 FOR DISPLAYING ALL BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 5 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY
PRESS 6 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 7 FOR SEARCHING A BOOK
PRESS 8 FOR BACK
4
ENTER THE GERNE OF BOOK YOU WANT TO DISPLAY
HISTORICAL
1 	 Grant 	 Ron_chernow 	 America_publishing 	 HISTORY 	 1
2 	 Embers_of_war 	 Fredrick_logevall 	 Blue_bridge 	 HISTORY 	 1
3 	 The_history_time 	 Susan_wiser 	 Arcadis_publishing 	 HISTORY 	 1
4 	 Embracing_defeat 	 John_dower 	 Black_dome 	 HISTORY 	 1
5 	 Hitler 	 Lan_kershaw 	 Alan_hood_company 	 HISTORY 	 1
6 	 Histor_of_rome 	 Mary_beard 	 America_publishing 	 HISTORY 	 1
7 	 The_crusades 	 Thomas_asbridge 	 Blue_bridge 	 HISTORY 	 1
8 	 The_womens_hour 	 Elanie_weiss 	 Arcadis_publishing 	 HISTORY 	 1
9 	 Churchill 	 Andres_roberts 	 Black_dome 	 HISTORY 	 1
10 	 Broken_lives 	 Konrad_jarausch 	 Alan_hood_company 	 HISTORY 	 1
11 	 Rites_of_spring 	 Modris_eksteins 	 America_publishing 	 HISTORY 	 1
12 	 Fredrick_douglas 	 David_blight 	 Blue_bridge 	 HISTORY 	 1
13 	 An_army_at_dawn 	 Rick_atkinson 	 Arcadis_publishing 	 HISTORY 	 1
14 	 Stalin_englishman 	 Andrew_lownie 	 Black_dome 	 HISTORY 	 1
15 	 Appeasement 	 Tim_bouverie 	 Alan_hood_company 	 HISTORY 	 2
16 	 the_gulf 	 Jack_davis 	 America_publishing 	 HISTORY 	 2
17 	 Sapiens 	 Yuval_harari 	 Blue_bridge 	 HISTORY 	 2
18 	 The_silk_roads 	 Peter_frankopan 	 Arcadis_publishing 	 HISTORY 	 2
19 	 The_fall_of_rome 	 Bryan_ward 	 Black_dome 	 HISTORY 	 2
20 	 Homo_deus 	 Yuval_naoh 	 Alan_hood_company 	 HISTORY 	 2
21 	 Raja_Mohan 	 Ravi_Mohan 	 Hunda_Publication 	 LITERATURE 	 3
ENTER THE TASK YOU WANT TO PERFORM
PRESS 1 FOR ADDING NEW BOOK TO THE LIBARY
PRESS 2 FOR BORROWING A BOOK FROM LIBARY
PRESS 3 FOR DISPLAYING ALL BOOK OF THE LIBARY
PRESS 4 FOR DISPLAYING ALL BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 5 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY
PRESS 6 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 7 FOR SEARCHING A BOOK
PRESS 8 FOR BACK
5
1 	 Malgudi_days 	 RK_narayan 	 Gupta_publication 	 LITERATURE 	 1
1 	 Grant 	 Ron_chernow 	 America_publishing 	 HISTORY 	 1
ENTER THE TASK YOU WANT TO PERFORM
PRESS 1 FOR ADDING NEW BOOK TO THE LIBARY
PRESS 2 FOR BORROWING A BOOK FROM LIBARY
PRESS 3 FOR DISPLAYING ALL BOOK OF THE LIBARY
PRESS 4 FOR DISPLAYING ALL BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 5 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY
PRESS 6 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 7 FOR SEARCHING A BOOK
PRESS 8 FOR BACK
6
ENTER THE GERNE OF BOOK YOU WANT TO DISPLAY
LITERATURE
1 	 Malgudi_days 	 RK_narayan 	 Gupta_publication 	 LITERATURE 	 1
ENTER THE TASK YOU WANT TO PERFORM
PRESS 1 FOR ADDING NEW BOOK TO THE LIBARY
PRESS 2 FOR BORROWING A BOOK FROM LIBARY
PRESS 3 FOR DISPLAYING ALL BOOK OF THE LIBARY
PRESS 4 FOR DISPLAYING ALL BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 5 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY
PRESS 6 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 7 FOR SEARCHING A BOOK
PRESS 8 FOR BACK
7
ENTER THE NAME OF THE BOOKMalgudi_days
1 	 Malgudi_days 	 RK_narayan 	 Gupta_publication 	 LITERATURE 	 1
ENTER THE TASK YOU WANT TO PERFORM
PRESS 1 FOR ADDING NEW BOOK TO THE LIBARY
PRESS 2 FOR BORROWING A BOOK FROM LIBARY
PRESS 3 FOR DISPLAYING ALL BOOK OF THE LIBARY
PRESS 4 FOR DISPLAYING ALL BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 5 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY
PRESS 6 FOR DISPLAYING ALL BORROWED BOOK OF THE LIBARY OF PARTICULAR SECTION
PRESS 7 FOR SEARCHING A BOOK
PRESS 8 FOR BACK
8
ENTER THE SECTION THE SECTION EHICH YOU WANT TO INQUIRE TODAY
PRESS 1 FOR BOOKS
PRESS 2 FOR MAGZINE
PRESS 3 FOR NEWSPAPER
PRESS 4 FOR QUIT
2
ENTER THE TASK YOU WANT TO PERFORM
PRESS 1 FOR ADDING NEW MAGZINE TO THE LIBARY
PRESS 2 FOR BORROWING A MAGZINE FROM LIBARY
PRESS 3 FOR DISPLAYING ALL MAGZINE OF THE LIBARY
PRESS 4 FOR DISPLAYING ALL BORROWED MAGZINE OF THE LIBARY
PRESS 5 FOR SEARCHING A MAGZINE
PRESS 6 FOR BACK
1
ENTER THE NAME OF THE MAGZINEHanes
ENTER THE PUBLISHER OF THE MAGZINEKOrean_Publication
Record added
ENTER THE TASK YOU WANT TO PERFORM
PRESS 1 FOR ADDING NEW MAGZINE TO THE LIBARY
PRESS 2 FOR BORROWING A MAGZINE FROM LIBARY
PRESS 3 FOR DISPLAYING ALL MAGZINE OF THE LIBARY
PRESS 4 FOR DISPLAYING ALL BORROWED MAGZINE OF THE LIBARY
PRESS 5 FOR SEARCHING A MAGZINE
PRESS 6 FOR BACK
2
Traceback (most recent call last):
  File "C:\Users\student\Desktop\LIBARYMANAGMENT\mainprogram.py", line 76, in <module>
    magzinboroowed.borrowmagzine()
NameError: name 'magzinboroowed' is not defined
>>> 
